name: Update Cloudinary Photo List

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *' # Every hour

jobs:
  update-photos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cloudinary SDK
        run: npm install cloudinary

      - name: Run photo list generator
        run: node scripts/updatePhotos.js
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      - name: Commit and push photos.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add photos.json
          git commit -m "Auto-update photos.json" || echo "No changes"
          git push
